blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import (BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView,
                        status_published)

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('detail/<int:pk>/', cache_page(60)(BlogDetailView.as_view()), name='blog_detail'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='blog_update'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
    path('published/<int:pk>/', status_published, name='status_published'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

NULLABLE = {'null': True, 'blank': True}


class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name='заголовок')
    slug = models.CharField(max_length=150, verbose_name='slug', **NULLABLE)
    body = models.TextField(verbose_name='содержимое')
    image = models.ImageField(upload_to='blog/', verbose_name='превью', **NULLABLE)
    created_at = models.DateField(verbose_name='дата создания', auto_now_add=True)
    is_published = models.BooleanField(verbose_name='опубликовано', default=True)
    views_count = models.PositiveSmallIntegerField(verbose_name='количество просмотров', default=0)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'пост'
        verbose_name_plural = 'посты'
        ordering = ('created_at',)

blog/forms.py
from django import forms

from blog.models import Blog


class BlogForm(forms.ModelForm):

    class Meta:
        model = Blog
        fields = ('title', 'body', 'is_published', 'image')

blog/views.py
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify

from blog.forms import BlogForm
from blog.models import Blog


class BlogListView(ListView):
    """Для отображения списков опубликованных постов"""
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogCreateView(CreateView):
    """Для создания нового поста"""
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('blog:blog_list')

    def form_valid(self, form):
        """Обрабатывает корректную форму и сохраняет новый пост"""
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()

        return super().form_valid(form)


class BlogDetailView(DetailView):
    """Для отображения деталей поста"""
    model = Blog

    def get_object(self, queryset=None):
        """Увеличивает количество просмотров поста каждый раз, когда его просматривают"""
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogUpdateView(UpdateView):
    """Для обновления существующего поста"""
    model = Blog
    form_class = BlogForm

    def form_valid(self, form):
        """Обрабатывает корректную форму и обновляет пост"""
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()

        return super().form_valid(form)

    def get_success_url(self):
        """Определяет URL для редиректа после успешного обновления поста"""
        return reverse('blog:blog_detail', args=[self.kwargs.get('pk')])


class BlogDeleteView(DeleteView):
    """Для удаления поста"""
    model = Blog
    success_url = reverse_lazy('blog:blog_list')


def status_published(request, pk):
    """Изменяет статус публикации поста. Редирект на домашнюю страницу после изменения статуса"""
    blog_item = get_object_or_404(Blog, pk=pk)
    if blog_item.is_published:
        blog_item.is_published = False
    else:
        blog_item.is_published = True

    blog_item.save()

    return redirect(reverse('main:home'))

blog/templates/blog/blog_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить материал "{{ object.title }}"?</p>
                        <button type="submit" class="btn bg-danger">Подтвердить</button>
                        <a href="{% url 'blog:list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'main/base.html' %}
{% block content %}
<div class="d-md-flex flex-md-equal w-100 my-md-3 ps-md-3">
    <div class="bg-dark me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center text-white overflow-hidden">
        <div class="my-3 py-3">
            <h2 class="display-5">Материал "{{ object.title }}" ({{ object.slug }})</h2>
            <p class="lead">{{ object.body | slice:100 }}</p>
            <!--                <a class="btn btn-outline-secondary" href="">Просмотр</a>-->
        </div>
        <div class="lead">
            Просмотры {{ object.views_count }}
        </div>
        <div class="bg-light shadow-sm mx-auto"
             style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;">
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'main/base.html' %}

{% block content %}
<div class="col-6">
    <div class="card">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">
                    Добавление материала
                </h3>
            </div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                </form>
            </div>
            <div class="card-footer"></div>
        </div>
    </div>
</div>
</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'main/base.html' %}
{% block content %}
    {% load my_tags_blog %}
    <div class="col-12 mb-5 text-center">
        {% if user.is_superuser %}
            <a class="btn btn-outline-secondary" href="{% url 'blog:blog_create' %}">Добавить материал</a>
        {% endif %}
    </div>
    <div class="d-md-flex flex-md-equal w-100 my-md-3 ps-md-3">
        {% for object in object_list %}
            <div class="bg-dark me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center text-white overflow-hidden">
                <div class="my-3 py-3">
                    <h2 class="display-5">{{ object.title }}</h2>
                    <img src={{ object.image | mymedia }} width="300" height="300">
                    <p class="lead">{{ object.body | slice:200 }}</p>
                    <a class="btn btn-outline-secondary"
                       href="{% url 'blog:blog_detail' object.pk %}"
                       role="button">Просмотр</a>
                    {% if user.is_superuser or user == object.owner %}
                        <a class="btn btn-outline-secondary"
                           href="{% url 'blog:blog_update' object.pk %}"
                           role="button">Редактировать</a>
                        <a class="btn btn-outline-secondary"
                           href="{% url 'blog:blog_delete' object.pk %}"
                           role="button">Удалить</a>
                    {% endif %}
                </div>
                {% if user.is_superuser or user == object.owner %}
                    {% if object.is_published %}
                        <a class="btn btn-outline-secondary"
                           href="{% url 'blog:status_published' object.pk %}">Убрать</a>
                    {% else %}
                        <a class="btn btn-outline-secondary"
                           href="{% url 'blog:status_published' object.pk %}">Добавить</a>
                    {% endif %}
                {% endif %}
            </div>
        {% endfor %}
    </div>
    </div>
    </div>
    </div>
{% endblock %}