blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import (BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView,
                        status_published)

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('detail/<int:pk>/', cache_page(60)(BlogDetailView.as_view()), name='blog_detail'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='blog_update'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
    path('published/<int:pk>/', status_published, name='status_published'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main.apps import MainConfig
from main.views import HomeView, DoctorsListView, DoctorsDetailView, AppointmentCreateView, ServicesListView, \
    ReviewsListView, ReviewsCreateView, ReviewsDeleteView, MedicalDiagView

app_name = MainConfig.name

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('medical_company/', MedicalDiagView.as_view(), name='medical_company'),
    path('doctors_list/', DoctorsListView.as_view(), name='doctors_list'),
    path('doctors_detail/<int:pk>/', DoctorsDetailView.as_view(), name='doctors_detail'),
    path('services_list/', ServicesListView.as_view(), name='services_list'),
    path('reviews_list/', ReviewsListView.as_view(), name='reviews_list'),
    path('reviews_create/', ReviewsCreateView.as_view(), name='reviews_create'),
    path('reviews_delete/<int:pk>/', ReviewsDeleteView.as_view(), name='reviews_delete'),
    path('create/appointment/<int:pk>/', AppointmentCreateView.as_view(), name='appointment_create'),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, email_verification

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('email-confirm/<str:token>/', email_verification, name='email-confirm'),
]

main/models.py
from django.db import models
from users.models import User

NULLABLE = {'null': True, 'blank': True}


class Specializations(models.Model):
    title = models.CharField(max_length=100, verbose_name='наименование')
    description = models.TextField(verbose_name='описание', **NULLABLE)

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'специализация'
        verbose_name_plural = 'специализации'


class Doctors(models.Model):
    last_name = models.CharField(max_length=100, verbose_name='фамилия')
    first_name = models.CharField(max_length=100, verbose_name='имя')
    middle_name = models.CharField(max_length=100, verbose_name='отчество', **NULLABLE)
    avatar = models.ImageField(upload_to='doctors/', verbose_name='фото', **NULLABLE)
    specialty = models.ForeignKey('Specializations', on_delete=models.CASCADE, verbose_name='специализация')
    experience_years = models.PositiveIntegerField(verbose_name='опыт работы (лет)', default=0)
    rating = models.DecimalField(max_digits=3, decimal_places=1, verbose_name='рейтинг', default=0.0)
    phone_number = models.CharField(max_length=15, verbose_name='номер телефона', **NULLABLE)
    email = models.EmailField(verbose_name='электронная почта', **NULLABLE)

    def __str__(self):
        return f'{self.last_name} {self.first_name}, Специализация: {self.specialty}, Рейтинг: {self.rating}, Опыт работы: {self.experience_years} лет'

    class Meta:
        verbose_name = 'врач'
        verbose_name_plural = 'врачи'


class Services(models.Model):
    title = models.CharField(max_length=100, verbose_name='наименование')
    description = models.TextField(verbose_name='описание', **NULLABLE)
    price = models.PositiveIntegerField(verbose_name='стоимость')
    doctor = models.ManyToManyField('Doctors', verbose_name='врач')
    specialty = models.ForeignKey(Specializations, on_delete=models.CASCADE, verbose_name='специализация')

    def __str__(self):
        return f'{self.title} - {self.price}'

    class Meta:
        verbose_name = 'услуга'
        verbose_name_plural = 'услуги'


class Reviews(models.Model):
    user_name = models.CharField(max_length=100, verbose_name='имя пользователя')
    review_text = models.TextField(verbose_name='текст отзыва')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')

    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='владелец', **NULLABLE)

    def str(self):
        return f'Отзыв {self.review_text} от {self.user_name}'

    class Meta:
        verbose_name = 'отзыв'
        verbose_name_plural = 'отзывы'
        ordering = ('-created_at',)


class Appointment(models.Model):
    doctor = models.ForeignKey(Doctors, on_delete=models.CASCADE, verbose_name='врач', **NULLABLE)
    patient = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='пациент')
    services = models.ForeignKey(Services, on_delete=models.CASCADE, verbose_name='выбранная услуга', **NULLABLE)
    appointment_date = models.DateTimeField(verbose_name='дата и время записи')

    def __str__(self):
        return f'Запись на прием: {self.patient} к {self.doctor} на {self.appointment_date}'

    class Meta:
        verbose_name = 'запись на прием'
        verbose_name_plural = 'записи на прием'
        ordering = ('appointment_date',)

main/forms.py
from django.forms import ModelForm

from main.models import Appointment


class AppointmentForm(ModelForm):
    class Meta:
        model = Appointment
        fields = ('appointment_date',)


class AppointmentProfileForm(ModelForm):
    class Meta:
        model = Appointment
        fields = ('services', 'appointment_date',)

main/views.py
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, DetailView, CreateView, DeleteView

from blog.models import Blog
from main.forms import AppointmentForm
from main.models import Doctors, Appointment, Services, Reviews


class MedicalDiagView(TemplateView):
    """Для отображения страницы о компании MedicalDiag"""
    template_name = 'main/medical_company.html'


class HomeView(TemplateView):
    """Главная страница приложения"""
    template_name = 'main/home.html'

    def get_context_data(self, *args, **kwargs):
        """Добавляет случайные посты в контекст для отображения на главной странице"""
        context_data = super().get_context_data(*args, **kwargs)

        random_blogs = Blog.objects.order_by('?')[:3]
        blog_article_title = [blog.title for blog in random_blogs]
        blog_article_pk = [blog.pk for blog in random_blogs]
        context_data['articles'] = dict(zip(blog_article_title, blog_article_pk))

        return context_data


class DoctorsListView(ListView):
    """Для отображения списка врачей"""
    model = Doctors
    context_object_name = 'specialty'

    def get_context_data(self, *args, **kwargs):
        """Добавляет специальности врачей в контекст"""
        context = super().get_context_data(*args, **kwargs)
        doctors = context['specialty']
        specialty_title = {}
        for doctor in doctors:
            specialty = doctor.specialty
            specialty_title['specialty'] = specialty.title
        context['specialty'] = specialty_title
        return context


class DoctorsDetailView(DetailView):
    """Для отображения деталей конкретного врача"""
    model = Doctors


class ServicesListView(ListView):
    """Для отображения списка услуг"""
    model = Services


class ReviewsListView(ListView):
    """Для отображения списка отзывов"""
    model = Reviews


class ReviewsCreateView(CreateView):
    """Для создания нового отзыва"""
    model = Reviews
    fields = ('review_text',)
    success_url = reverse_lazy('main:reviews_list')

    def form_valid(self, form):
        """Проверяет форму и сохраняет отзыв с установленными именем пользователя и владельцем"""
        form.instance.user_name = self.request.user.first_name
        form.instance.owner = self.request.user
        return super().form_valid(form)


class ReviewsDeleteView(DeleteView):
    """Для удаления отзыва"""
    model = Reviews
    success_url = reverse_lazy('main:reviews_list')


class AppointmentCreateView(CreateView):
    """Для создания новой записи на прием"""
    model = Appointment
    form_class = AppointmentForm
    success_url = reverse_lazy('main:home')

    def get_context_data(self, **kwargs):
        """Получает контекст для создания записи на прием"""
        context_data = super().get_context_data(**kwargs)
        services = get_object_or_404(Services, pk=self.kwargs['pk'])
        context_data['services'] = services
        return context_data

    def form_valid(self, form):
        """Проверяет форму и сохраняет запись на прием с установленным пациентом и услугой"""
        form.instance.patient = self.request.user
        form.instance.services = self.get_context_data()['services']
        return super().form_valid(form)

main/templates/main/appointment_form.html
{% extends 'main/base.html' %}
{% block content %}
<div class="container d-flex justify-content-center">
    <div class="col-8">
        <div class="card">
            <div class="card-header text-center">{{ services.title }}</div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success" style="width: 100%;">Записаться</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/base.html
{% load static %}
<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Carousel Template for Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/carousel/">

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <link href="{% static 'css/carousel.css' %}" rel="stylesheet">
</head>
<body>

<header>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="/">MedicalDiag</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'main:medical_company' %}">О нас <span
                            class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'blog:blog_list' %}">Статьи <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'main:doctors_list' %}">Врачи <span
                            class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'main:services_list' %}">Услуги <span
                            class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'main:reviews_list' %}">Отзывы <span
                            class="sr-only">(current)</span></a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'users:profile' %}">Личный кабинет <span
                                class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'users:logout' %}">Выйти <span
                                class="sr-only">(current)</span></a>
                    </li>
                {% else %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'users:login' %}">Войти <span
                                class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'users:register' %}">Регистрация <span
                                class="sr-only">(current)</span></a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
</header>

<main role="main">
    {% block content %}
    {% endblock %}
    <!-- FOOTER -->
    <hr>
    <footer class="container">
        <p class="float-right"><a href="#">Back to top</a></p>
        <p>&copy; {% now 'd-m-Y' %} &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
    </footer>
</main>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="
{% static '
js / jquery - slim.min.js
' %}"><\/script>'
)</script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- Just to make our placeholder images work. Don't actually copy the next line! -->
<script src="{% static 'js/holder.min.js' %}"></script>
</body>
</html>

main/templates/main/doctors_detail.html
{% extends 'main/base.html' %}
{% load my_tags %}
{% block content %}
    <style>
        .row {
            display: flex;
            justify-content: center;
            align-items: flex-start;
            height: 100vh;
        }

        .col-md-6 {
            width: 50%;
            text-align: center;
        }
    </style>
    <div class="row">
        <div class="col-md-6">
            <h2 class="featurette-heading">{{ object.last_name }} {{ object.first_name }} {{ object.middle_name }}</h2>
            <p class="lead">{{ object.specialty }}</p>
            <p class="lead">Стаж - {{ object.experience_years }} лет</p>
            <p class="lead">Рейтинг - {{ object.rating }}</p>
            {% if object.phone_number %}
                <p class="lead">Номер телефона - {{ object.phone_number }}</p>
            {% endif %}
            {% if object.email %}
                <p class="lead">Электронная почта - {{ object.email }}</p>
            {% endif %}
        </div>
        <div class="col-md-5">
            <img class="featurette-image img-fluid mx-auto" src="{{ object.avatar | media_filter }}" alt="фото врача"
                 width="260" height="450">
        </div>
    </div>
{% endblock %}

main/templates/main/doctors_list.html
{% extends 'main/base.html' %}
{% load my_tags %}
{% block content %}

    <div class="container marketing">
        <div class="row">
            {% for object in object_list %}
                <div class="col-lg-4">
                    <img src="{{ object.avatar | media_filter }}" alt="фото врача" width="360" height="550">
                    <h2>{{ object.last_name }} {{ object.first_name }} {{ object.middle_name }}</h2>
                    <p>{{ object.specialty }}</p>
                    <p><a class="btn btn-secondary" href="{% url 'main:doctors_detail' object.pk %}" role="button">Подробнее</a>
                    </p>
                </div><!-- /.col-lg-4 -->
            {% endfor %}
        </div><!-- /.row -->
    </div>

{% endblock %}

main/templates/main/home.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
    <main role="main">
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img class="first-slide"
                         src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw=="
                         alt="First slide">
                    <div class="container">
                        <div class="carousel-caption text-left">
                            <h1>Почему выбирают MedicalDiag?</h1>
                            <p>MedicalDiag предлагает высокий профессионализм благодаря квалифицированным специалистам и
                                современному оборудованию, предоставляя широкий спектр диагностических услуг с
                                индивидуальным подходом к каждому пациенту</p>
                            <p><a class="btn btn-lg btn-primary" href="{% url 'main:services_list' %}" role="button">Записаться
                                на прием</a></p>
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <img class="second-slide"
                         src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw=="
                         alt="Second slide">
                    <div class="container">
                        <div class="carousel-caption">
                            <h1>MedicalDiag заботится о вашем здоровье</h1>
                            <p>Мы обеспечиваем комфорт и удобство, включая
                                возможность онлайн-записи, а также предлагаем конкурентоспособные цены и акции,
                                гарантируя
                                высокие стандарты обслуживания и защиту конфиденциальности информации</p>
                            <p><a class="btn btn-lg btn-primary" href="{% url 'main:services_list' %}" role="button">Записаться
                                на прием</a></p>
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <img class="third-slide"
                         src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw=="
                         alt="Third slide">
                    <div class="container">
                        <div class="carousel-caption text-right">
                            <h1>Ваши отзывы важны для нас</h1>
                            <p>Положительные отзывы
                                довольных клиентов подтверждают нашу репутацию, а постоянное совершенствование знаний и
                                навыков специалистов позволяет нам оставаться надежным партнером в диагностике
                                здоровья</p>
                            {% if user.is_authenticated %}
                            <p><a class="btn btn-lg btn-primary" href="{% url 'main:reviews_create' %}" role="button">Добавить отзыв</a></p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>

        <div class="container marketing">

            <div class="row">
                {% for article, pk in articles.items %}
                    <div class="col-lg-4">
                        <img class="rounded-circle"
                             src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw=="
                             alt="Generic placeholder image" width="140" height="140">
                        <h3>{{ article }}</h3>
                        <td><a class="p-2 btn btn-primary"
                               href="{% url 'blog:blog_detail' pk %}">Перейти к статье</a>
                        </td>
                    </div><!-- /.col-lg-4 -->
                {% endfor %}
            </div><!-- /.row -->


            <!-- START THE FEATURETTES -->

            <hr class="featurette-divider">

            <div class="row featurette">
                <div class="col-md-7">
                    <h2 class="featurette-heading">Высокие стандарты обслуживания<span
                            class="text-muted">...</span></h2>
                    <p class="lead">Мы заботимся о каждом пациенте и гарантируем высокий уровень сервиса на всех
                        этапах – от записи до получения результатов.</p>
                </div>
                <div class="col-md-5">
                    <img src="{% static 'home/home_1.jpg' %}" width="300" height="300">
                </div>
            </div>

            <hr class="featurette-divider">

            <div class="row featurette">
                <div class="col-md-7 order-md-2">
                    <h2 class="featurette-heading">Конфиденциальность и безопасность<span
                            class="text-muted">...</span></h2>
                    <p class="lead">Мы строго соблюдаем нормы конфиденциальности и защиты данных, обеспечивая
                        безопасность личной информации наших пациентов.</p>
                </div>
                <div class="col-md-5 order-md-1">
                    <img src="{% static 'home/home_2.jpg' %}" width="300" height="300">
                </div>
            </div>

            <hr class="featurette-divider">

            <div class="row featurette">
                <div class="col-md-7">
                    <h2 class="featurette-heading">Постоянное совершенствование<span class="text-muted">...</span></h2>
                    <p class="lead">Мы постоянно обновляем наши знания и навыки, участвуем в семинарах и
                        конференциях, чтобы быть в курсе последних достижений в области медицины.</p>
                </div>
                <div class="col-md-5">
                    <img src="{% static 'home/home_3.jpg' %}" width="300" height="300">
                </div>
            </div>

            <hr class="featurette-divider">

            <!-- /END THE FEATURETTES -->

        </div><!-- /.container -->
    </main>
{% endblock %}

main/templates/main/medical_company.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
    <div class="card mb-3">
        <img class="card-img-top" src="{% static 'home/about.jpg' %}">
        <div class="card-body">
            <h2 class="card-title">О компании</h2>
            <h5 class="card-title">История компании</h5>
            <p class="card-text">Наш медицинский центр был основан в 2010 году с целью предоставления высококачественных
                медицинских услуг в комфортной и дружелюбной обстановке. С тех пор мы выросли и расширили спектр своих
                услуг, объединяя передовые технологии и опытные кадры. Наша команда состоит из квалифицированных врачей
                и медицинских работников, которые постоянно повышают свою квалификацию и следят за последними
                достижениями в области медицины.</p>
        </div>
        <div class="card-body">
            <h5 class="card-title">Миссия и ценности</h5>
            <p class="card-text">Наша миссия — обеспечивать доступ к качественной медицинской помощи для каждого
                пациента, поддерживая его здоровье и благополучие на каждом этапе жизни. Мы стремимся создать атмосферу
                доверия и комфорта, где каждый пациент чувствует себя услышанным и важным.

                Наши ценности:
                - Качество: Мы гарантируем высокие стандарты медицинского обслуживания.
                - Человечность: Мы относимся к каждому пациенту с уважением и заботой.
                - Инновации: Мы внедряем современные технологии и методы лечения.
                - Командная работа: Мы работаем вместе, чтобы достичь наилучших результатов для наших пациентов.

                Мы гордимся тем, что можем быть частью здоровья и жизни наших пациентов!</p>
        </div>
        <div class="card" style="width: 18rem;">
            <div class="card-header">
                Наши контакты
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">8(800)1002030</li>
                <li class="list-group-item">medecaldiag@mail.ru</li>
                <li class="list-group-item">Московская область, г.Подольск, ул.Ленина, д.10</li>
                <li class="list-group-item">
                   <img src="{% static 'icon/icon_odnoklassniki.png' %}" width="30" height="30"> 
                   <img src="{% static 'icon/icon_telegram.png' %}" width="30" height="30"> 
                   <img src="{% static 'icon/icon_vk.png' %}" width="30" height="30"> 
                </li>
            </ul>
        </div>
        </div>
{% endblock %}

main/templates/main/reviews_confirm_delete.html
{% extends 'main/base.html' %}
{% block content %}
<div class="container d-flex justify-content-center">
    <div class="col-8">
        <div class="card">
            <div class="card-header text-center">Удалить отзыв от {{ object.created_at }}</div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    <div class="card">
                        <div class="card-body">
                            {% csrf_token %}
                            <p class="card-text">{{ object.review_text }}</p>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-success flex-fill me-2">Подтвердить удаление</button>
                        <a class="btn btn-warning flex-fill ms-2" href="{% url 'main:reviews_list' %}">Отмена</a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/reviews_form.html
{% extends 'main/base.html' %}
{% block content %}
<div class="container d-flex justify-content-center">
    <div class="col-8">
        <div class="card">
            <div class="card-header text-center">Написать отзыв</div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    <div class="card">
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                        </div>
                    </div>
                    <button type="submit" class="btn btn-success" style="width: 100%;">
                        Отправить отзыв
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/reviews_list.html
{% extends 'main/base.html' %}
{% block content %}

<div class="col-12 mb-5 text-center">
    {% if user.is_authenticated %}
    <a class="btn btn-outline-secondary" href="{% url 'main:reviews_create' %}">Добавить отзыв</a>
    {% endif %}
</div>

<div class="card-container" style="display: flex; flex-wrap: wrap; justify-content: center; gap: 1rem;">
    {% for object in object_list %}
    <div class="card text-white bg-secondary" style="max-width: 18rem;">
        <div class="card-header">Отзыв от {{ object.created_at }}</div>
        <div class="card-body">
            <h5 class="card-title">{{ object.user_name }}</h5>
            <p class="card-text">{{ object.review_text }}</p>
        </div>
        {% if user.is_superuser or user == object.owner %}
        <div class="d-flex justify-content-center mb-3">
            <a class="btn btn-danger" href="{% url 'main:reviews_delete' object.pk %}">Удалить</a>
        </div>
        {% endif %}
    </div>
    {% endfor %}
</div>

{% endblock %}

main/templates/main/services_list.html
{% extends 'main/base.html' %}
{% block content %}
<div class="container marketing">
    <h1 class="title">
        Все услуги MedicalDiag
    </h1>
    <div class="row">
        {% for object in object_list %}
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <table class="table">
                        <tr>
                            <td>Наименование</td>
                            <td>{{ object.title }}</td>
                        </tr>
                        <tr>
                            <td>Описание</td>
                            <td>{{ object.description }}</td>
                        </tr>
                        <tr>
                            <td>Врач</td>
                            <td>{{ object.specialty }}</td>
                        </tr>
                        <tr>
                            <td>Цена</td>
                            <td>{{ object.price }} &#8381</td>
                        </tr>
                    </table>
                </div>
                {% if user.is_authenticated %}
                <a class="btn btn-secondary" href="{% url 'main:appointment_create' object.pk %}" role="button">Выбрать
                    услугу</a>
                {% endif %}
                <div class="card-footer"></div>
            </div>
        </div><!-- /.col-lg-4 -->
        {% endfor %}
    </div><!-- /.row -->
</div>
{% endblock %}